/**
 * Sidebar Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type SidebarVersion = string;
interface SidebarProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: SidebarVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  children?: React.ReactNode;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/sidebar.json');
} catch (e) {
  // console.warn('Config not found for sidebar');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./sidebar-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./sidebar-holo-frame.tsx')),
  'data-panel': lazy(() => import('./sidebar-data-panel.tsx')),
  'circuit-board': lazy(() => import('./sidebar-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./sidebar-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./sidebar-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./sidebar-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./sidebar-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./sidebar-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./sidebar-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-[240px] h-full rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, SidebarProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackSidebar';

// Main Component
const SidebarBase = React.forwardRef<HTMLElement, SidebarProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
SidebarBase.displayName = 'Sidebar';

export const Sidebar = SidebarBase;

export default Sidebar;


