/**
 * Typography Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type TypographyVersion = string;
interface TypographyProps extends React.HTMLAttributes<HTMLElement> {
  version?: TypographyVersion;
  variant?: 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote' | 'code' | 'lead' | 'large' | 'small' | 'muted';
  as?: React.ElementType;
  color?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/typography.json');
} catch (e) {
  // console.warn('Config not found for typography');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./typography-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./typography-holo-frame.tsx')),
  'data-panel': lazy(() => import('./typography-data-panel.tsx')),
  'circuit-board': lazy(() => import('./typography-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./typography-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./typography-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./typography-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./typography-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./typography-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./typography-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="h-6 w-1/3 bg-muted/20 animate-pulse rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, TypographyProps>(({ 
  children, 
  className = '',
  version,
  variant = 'p',
  as,
  ...props 
}, ref) => {
    const Comp = as || (['h1', 'h2', 'h3', 'h4', 'p', 'blockquote', 'code'].includes(variant) ? variant : 'p');
    // @ts-ignore
    return <Comp ref={ref} className={className} {...props}>{children}</Comp>;
});
FallbackComponent.displayName = 'FallbackTypography';

// Main Component
const TypographyBase = React.forwardRef<HTMLElement, TypographyProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
TypographyBase.displayName = 'Typography';

export const Typography = TypographyBase;

export default Typography;


