/**
 * Item Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type ItemVersion = string;
interface ItemProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: ItemVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  children?: React.ReactNode;
  active?: boolean;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/item.json');
} catch (e) {
  // console.warn('Config not found for item');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./item-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./item-holo-frame.tsx')),
  'data-panel': lazy(() => import('./item-data-panel.tsx')),
  'circuit-board': lazy(() => import('./item-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./item-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./item-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./item-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./item-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./item-matrix-grid.tsx')),
  'neon': lazy(() => import('./item-neon.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-12 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, ItemProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackItem';

// Main Component
const ItemBase = React.forwardRef<HTMLElement, ItemProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
ItemBase.displayName = 'Item';

export const Item = ItemBase;

export default Item;


