/**
 * InputOtp Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type InputOtpVersion = string;
interface InputOtpProps {
  version?: InputOtpVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  maxLength?: number;
  value?: string;
  onChange?: (value: string) => void;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/input-otp.json');
} catch (e) {
  // console.warn('Config not found for input-otp');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./input-otp-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./input-otp-holo-frame.tsx')),
  'data-panel': lazy(() => import('./input-otp-data-panel.tsx')),
  'circuit-board': lazy(() => import('./input-otp-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./input-otp-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./input-otp-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./input-otp-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./input-otp-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./input-otp-matrix-grid.tsx')),
  'neon': lazy(() => import('./input-otp-neon.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-14 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, InputOtpProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackInputOtp';

// Main Component
const InputOtpBase = React.forwardRef<HTMLElement, InputOtpProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
InputOtpBase.displayName = 'InputOtp';

export const InputOtp = InputOtpBase;

export default InputOtp;


