/**
 * Avatar Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';
// import type { AvatarProps, AvatarVersion } from '../../types/components/avatar.js';

// Fallback types if file doesn't exist
type AvatarVersion = string;
interface AvatarProps extends React.HTMLAttributes<HTMLElement> {
  version?: AvatarVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/avatar.json');
} catch (e) {
  // console.warn('Config not found for avatar');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./avatar-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./avatar-holo-frame.tsx')),
  'data-panel': lazy(() => import('./avatar-data-panel.tsx')),
  'circuit-board': lazy(() => import('./avatar-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./avatar-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./avatar-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./avatar-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./avatar-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./avatar-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./avatar-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-full min-h-[40px] rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, AvatarProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackAvatar';

// Subcomponents

export const AvatarImage = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ children, className = '', ...props }, ref) => (
  <div ref={ref} className={`ui-avatar-image ${className}`} {...props}>
    {children}
  </div>
));
AvatarImage.displayName = 'AvatarImage';

export const AvatarFallback = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(({ children, className = '', ...props }, ref) => (
  <div ref={ref} className={`ui-avatar-fallback ${className}`} {...props}>
    {children}
  </div>
));
AvatarFallback.displayName = 'AvatarFallback';

// Main Component
const AvatarBase = React.forwardRef<HTMLElement, AvatarProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
AvatarBase.displayName = 'Avatar';

export const Avatar = Object.assign(AvatarBase, {
  Image: AvatarImage,
  Fallback: AvatarFallback,
});

export default Avatar;

