/**
 * Direction Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type DirectionVersion = string;
interface DirectionProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: DirectionVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  direction?: 'up' | 'down' | 'left' | 'right' | 'ne' | 'nw' | 'se' | 'sw';
  size?: 'sm' | 'md' | 'lg';
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/direction.json');
} catch (e) {
  // console.warn('Config not found for direction');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./direction-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./direction-holo-frame.tsx')),
  'data-panel': lazy(() => import('./direction-data-panel.tsx')),
  'circuit-board': lazy(() => import('./direction-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./direction-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./direction-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./direction-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./direction-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./direction-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./direction-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-12 h-12 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, DirectionProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackDirection';

// Main Component
const DirectionBase = React.forwardRef<HTMLElement, DirectionProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
DirectionBase.displayName = 'Direction';

export const Direction = DirectionBase;

export default Direction;


