/**
 * Empty Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';
// import type { EmptyProps, EmptyVersion } from '../../types/components/empty.js';

// Fallback types if file doesn't exist
type EmptyVersion = string;
interface EmptyProps extends React.HTMLAttributes<HTMLElement> {
  version?: EmptyVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/empty.json');
} catch (e) {
  // console.warn('Config not found for empty');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./empty-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./empty-holo-frame.tsx')),
  'data-panel': lazy(() => import('./empty-data-panel.tsx')),
  'circuit-board': lazy(() => import('./empty-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./empty-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./empty-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./empty-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./empty-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./empty-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./empty-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-full min-h-[40px] rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, EmptyProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackEmpty';

// Subcomponents

// Main Component
const EmptyBase = React.forwardRef<HTMLElement, EmptyProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
EmptyBase.displayName = 'Empty';

export const Empty = EmptyBase;

export default Empty;

