/**
 * InputGroup Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type InputGroupVersion = string;
interface InputGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: InputGroupVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  children?: React.ReactNode;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/input-group.json');
} catch (e) {
  // console.warn('Config not found for input-group');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./input-group-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./input-group-holo-frame.tsx')),
  'data-panel': lazy(() => import('./input-group-data-panel.tsx')),
  'circuit-board': lazy(() => import('./input-group-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./input-group-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./input-group-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./input-group-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./input-group-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./input-group-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./input-group-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-10 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, InputGroupProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackInputGroup';

// Main Component
const InputGroupBase = React.forwardRef<HTMLElement, InputGroupProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
InputGroupBase.displayName = 'InputGroup';

export const InputGroup = InputGroupBase;

export default InputGroup;


