const fs = require('fs');
const path = require('path');

const COMPONENT_NAME = 'drawer';
const VERSIONS = [
  'angular-corner',
  'holo-frame',
  'data-panel',
  'circuit-board',
  'quantum-gate',
  'tactical-hud',
  'energy-shield',
  'terminal-window',
  'matrix-grid',
  'neon-outline'
];

const TARGET_DIR = path.join(__dirname, `../src/ui/components/${COMPONENT_NAME}`);

if (!fs.existsSync(TARGET_DIR)) {
  fs.mkdirSync(TARGET_DIR, { recursive: true });
}

// Helper to generate the component file content
const TEMPLATE = (version) => {
  let clipPath = 'none';
  
  switch (version) {
    case 'angular-corner':
      clipPath = 'polygon(20px 0, 100% 0, 100% 100%, 0 100%, 0 20px)';
      break;
    default:
      clipPath = 'inset(0 0 0 0 round 16px 16px 0 0)';
  }

  return `
import * as React from "react"
import { Drawer as VaulDrawer } from "vaul"
import { cn } from "../../utils/component-helpers"
import { X } from "lucide-react"

interface DrawerProps {
  version?: string
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info'
  type?: 'default' | 'outline' | 'solid' | 'ghost'
  children?: React.ReactNode
  className?: string
  content?: React.ReactNode
}

const Component = React.forwardRef<HTMLDivElement, DrawerProps>(({
  version = '${version}',
  variant = 'primary',
  type = 'default',
  children,
  className,
  content,
  ...props
}, ref) => {
  
  const colorMap: Record<string, string> = {
    neutral: 'primary', success: 'success', warning: 'warning', info: 'info', destructive: 'destructive', primary: 'primary'
  };
  const color = colorMap[variant] || 'primary';

  const getTypeStyles = () => {
    const baseColor = \`hsl(var(--\${color}-base))\`;
    switch(type) {
      case 'outline': return { borderTop: \`2px solid \${baseColor}\`, background: 'black' };
      case 'solid': return { background: \`hsl(var(--\${color}-base) / 0.1)\`, border: 'none' };
      default: return { 
        background: 'black', 
        borderTop: \`1px solid hsl(var(--\${color}-base) / 0.5)\`,
        boxShadow: \`0 -4px 20px -5px hsl(var(--\${color}-base) / 0.3)\`
      };
    }
  };

  const styles = getTypeStyles();

  return (
    <VaulDrawer.Root>
      <VaulDrawer.Trigger asChild>
        {children || <button className="px-4 py-2 border rounded">Open Drawer</button>}
      </VaulDrawer.Trigger>
      <VaulDrawer.Portal>
        <VaulDrawer.Overlay className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50" />
        <VaulDrawer.Content 
          className={cn(
            "bg-black flex flex-col rounded-t-[10px] fixed bottom-0 left-0 right-0 max-h-[96%] z-50 focus:outline-none",
            className
          )}
          style={{
            ...styles,
            clipPath: '${clipPath}',
            color: \`hsl(var(--\${color}-foreground))\`
          }}
        >
           <div className="mx-auto w-12 h-1.5 flex-shrink-0 rounded-full bg-gray-600 my-4" />
           <div className="p-6 pb-8 min-h-[300px]">
             <div className="flex justify-between items-center mb-6">
               <VaulDrawer.Title className="font-mono text-xl font-bold tracking-tight uppercase" style={{ color: \`hsl(var(--\${color}-base))\` }}>
                 {version.replace('-', ' ')} PANEL
               </VaulDrawer.Title>
               <VaulDrawer.Close asChild>
                 <button className="p-2 hover:bg-white/10 rounded-full transition-colors">
                   <X className="w-5 h-5 opacity-70" />
                 </button>
               </VaulDrawer.Close>
             </div>
             
             {content || (
               <div className="space-y-4 text-gray-400 font-mono text-sm">
                 <p>SYSTEM ACCESS GRANTED.</p>
                 <p>Analyzing component version: <span className="text-white">{version}</span></p>
                 <div className="h-32 border border-dashed border-gray-800 rounded flex items-center justify-center bg-gray-900/50">
                   NO DATA SIGNAL
                 </div>
               </div>
             )}
           </div>
        </VaulDrawer.Content>
      </VaulDrawer.Portal>
    </VaulDrawer.Root>
  )
})

Component.displayName = "Drawer-${version}"

export default Component
`;
};

// Generate each version
VERSIONS.forEach(version => {
  const content = TEMPLATE(version);
  const filePath = path.join(TARGET_DIR, `${COMPONENT_NAME}-${version}.tsx`);
  fs.writeFileSync(filePath, content);
  console.log(`Generated ${COMPONENT_NAME}-${version}.tsx`);
});

// Generate index.tsx
const indexContent = `/**
 * Drawer Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type DrawerVersion = string;
interface DrawerProps {
  version?: DrawerVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  children?: React.ReactNode;
  content?: React.ReactNode;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/${COMPONENT_NAME}.json');
} catch (e) {
  // console.warn('Config not found for ${COMPONENT_NAME}');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
${VERSIONS.map(v => `  '${v}': lazy(() => import('./${COMPONENT_NAME}-${v}')),`).join('\n')}
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-10 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, DrawerProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={\`p-4 border border-dashed border-red-500/50 bg-red-500/10 \${className}\`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackDrawer';

// Main Component
const DrawerBase = React.forwardRef<HTMLElement, DrawerProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
DrawerBase.displayName = 'Drawer';

export const Drawer = DrawerBase;

export default Drawer;
`;

fs.writeFileSync(path.join(TARGET_DIR, 'index.tsx'), indexContent);
console.log('Generated index.tsx');

// Update main index.ts export
const mainIndexInitPath = path.join(__dirname, '../src/ui/index.ts');
let mainIndexContent = fs.readFileSync(mainIndexInitPath, 'utf8');

// Check if already exported
if (!mainIndexContent.includes("export * from './components/drawer'")) {
    // Add to components section
    const exportStatement = "export * from './components/drawer';";
    // Find a good place to insert (e.g. after direction)
    if (mainIndexContent.includes("export * from './components/direction';")) {
        mainIndexContent = mainIndexContent.replace(
            "export * from './components/direction';",
            "export * from './components/direction';\n" + exportStatement
        );
    } else {
        // Append to end if specific place not found
        mainIndexContent += `\n${exportStatement}`;
    }
    fs.writeFileSync(mainIndexInitPath, mainIndexContent);
    console.log('Updated src/ui/index.ts with export');
}

console.log('Drawer regeneration complete.');
