const fs = require('fs');
const path = require('path');

const COMPONENT_NAME = 'sonner';
const VERSIONS = [
  'angular-corner',
  'holo-frame',
  'data-panel',
  'circuit-board',
  'quantum-gate',
  'tactical-hud',
  'energy-shield',
  'terminal-window',
  'matrix-grid',
  'neon-outline'
];

const TARGET_DIR = path.join(__dirname, `../src/ui/components/${COMPONENT_NAME}`);

if (!fs.existsSync(TARGET_DIR)) {
  fs.mkdirSync(TARGET_DIR, { recursive: true });
}

// Helper to generate the component file content
const TEMPLATE = (version) => {
  return `
import * as React from "react"
import { Toaster as SonnerToaster } from "sonner"
import { cn } from "../../utils/component-helpers"

type ToasterProps = React.ComponentProps<typeof SonnerToaster> & {
    version?: string
    variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info'
}

const Component = React.forwardRef<HTMLElement, ToasterProps>(({ 
    version = '${version}', 
    variant = 'primary', 
    className, 
    theme = "dark", 
    ...props 
}, ref) => {
  
  // Custom styles based on version
  const getToastStyles = () => {
     switch('${version}') {
         case 'angular-corner':
             return {
                 toast: "group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg group-[.toaster]:rounded-none group-[.toaster]:clip-path-polygon-[0_0,100%_0,100%_85%,90%_100%,0_100%]",
                 description: "group-[.toast]:text-muted-foreground",
                 actionButton: "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
                 cancelButton: "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
             }
         case 'neon-outline':
             return {
                 toast: "group toast group-[.toaster]:bg-black group-[.toaster]:text-foreground group-[.toaster]:border group-[.toaster]:border-[hsl(var(--primary-base))] group-[.toaster]:shadow-[0_0_10px_hsl(var(--primary-base)/0.5)]",
                 description: "group-[.toast]:text-muted-foreground",
                 actionButton: "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
                 cancelButton: "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
             }
         default:
             return {
                 toast: "group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg",
                 description: "group-[.toast]:text-muted-foreground",
                 actionButton: "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
                 cancelButton: "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
             }
     }
  }

  const styles = getToastStyles();

  return (
    // @ts-ignore
    <SonnerToaster
      theme={theme as "light" | "dark" | "system"}
      className="toaster group"
      toastOptions={{
        classNames: styles,
      }}
      {...props}
    />
  )
})

Component.displayName = "Sonner-${version}"

export default Component
`;
};

// Generate each version
VERSIONS.forEach(version => {
  const content = TEMPLATE(version);
  const filePath = path.join(TARGET_DIR, `${COMPONENT_NAME}-${version}.tsx`);
  fs.writeFileSync(filePath, content);
  console.log(`Generated ${COMPONENT_NAME}-${version}.tsx`);
});

// Generate index.tsx
const indexContent = `/**
 * Sonner Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';
import { Toaster as SonnerToaster } from "sonner"

// Fallback types if file doesn't exist
type SonnerVersion = string;
type ToasterProps = React.ComponentProps<typeof SonnerToaster> & {
    version?: SonnerVersion
    variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info'
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/${COMPONENT_NAME}.json');
} catch (e) {
  // console.warn('Config not found for ${COMPONENT_NAME}');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
${VERSIONS.map(v => `  '${v}': lazy(() => import('./${COMPONENT_NAME}-${v}')),`).join('\n')}
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="fixed bottom-4 right-4 w-[356px] h-[60px] bg-muted/20 animate-pulse rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, ToasterProps>(({ 
  version,
  ...props 
}, ref) => (
  <SonnerToaster {...props} />
));
FallbackComponent.displayName = 'FallbackSonner';

// Main Component
const SonnerBase = React.forwardRef<HTMLElement, ToasterProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
SonnerBase.displayName = 'Sonner';

export const Sonner = SonnerBase;

export default Sonner;
`;

fs.writeFileSync(path.join(TARGET_DIR, 'index.tsx'), indexContent);
console.log('Generated index.tsx');

// Update main index.ts export
const mainIndexInitPath = path.join(__dirname, '../src/ui/index.ts');
let mainIndexContent = fs.readFileSync(mainIndexInitPath, 'utf8');

// Check if already exported
if (!mainIndexContent.includes("export * from './components/sonner'")) {
    // Add to components section
    const exportStatement = "export * from './components/sonner';";
    // Find a good place to insert
    if (mainIndexContent.includes("export * from './components/sidebar';")) {
        mainIndexContent = mainIndexContent.replace(
            "export * from './components/sidebar';",
            "export * from './components/sidebar';\n" + exportStatement
        );
    } else {
        // Append to end if specific place not found
        mainIndexContent += `\n${exportStatement}`;
    }
    fs.writeFileSync(mainIndexInitPath, mainIndexContent);
    console.log('Updated src/ui/index.ts with export');
}

console.log('Sonner regeneration complete.');
