const fs = require('fs');
const path = require('path');

const COMPONENT_NAME = 'item';
const VERSIONS = [
  'angular-corner',
  'holo-frame',
  'data-panel',
  'circuit-board',
  'quantum-gate',
  'tactical-hud',
  'energy-shield',
  'terminal-window',
  'matrix-grid',
  'neon-outline'
];

const TARGET_DIR = path.join(__dirname, `../src/ui/components/${COMPONENT_NAME}`);

if (!fs.existsSync(TARGET_DIR)) {
  fs.mkdirSync(TARGET_DIR, { recursive: true });
}

// Helper to generate the component file content
const TEMPLATE = (version) => {
  let clipPath = 'none';
  
  switch (version) {
    case 'angular-corner':
      clipPath = 'polygon(10px 0, 100% 0, 100% calc(100% - 10px), calc(100% - 10px) 100%, 0 100%, 0 10px)';
      break;
    default:
      clipPath = 'inset(0 0 0 0 round 4px)';
  }

  return `
import * as React from "react"
import { cn } from "../../utils/component-helpers"
import { ChevronRight } from "lucide-react"

interface ItemProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: string
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info'
  type?: 'default' | 'outline' | 'solid' | 'ghost'
  children?: React.ReactNode
  active?: boolean
}

const Component = React.forwardRef<HTMLDivElement, ItemProps>(({
  version = '${version}',
  variant = 'primary',
  type = 'default',
  children,
  className,
  active,
  ...props
}, ref) => {
  
  const colorMap: Record<string, string> = {
    neutral: 'primary', success: 'success', warning: 'warning', info: 'info', destructive: 'destructive', primary: 'primary'
  };
  const color = colorMap[variant] || 'primary';

  const getTypeStyles = (isActive: boolean) => {
    const baseColor = \`hsl(var(--\${color}-base))\`;
    if (isActive) {
       return { 
         borderColor: baseColor,
         background: \`hsl(var(--\${color}-base) / 0.15)\`
       };
    }

    switch(type) {
      case 'outline': return { border: \`1px solid \${baseColor}\`, background: 'transparent' };
      case 'solid': return { background: \`hsl(var(--\${color}-base) / 0.1)\`, border: 'none' };
      case 'ghost': return { background: 'transparent', border: 'none' };
      default: return { 
        background: \`hsl(var(--\${color}-base) / 0.05)\`, 
        border: \`1px solid hsl(var(--\${color}-base) / 0.2)\` 
      };
    }
  };

  const styles = getTypeStyles(!!active);

  return (
    <div
      ref={ref}
      className={cn(
        "flex items-center p-3 w-full transition-all duration-200 cursor-pointer hover:brightness-125",
        "group relative overflow-hidden",
        className
      )}
      style={{
        ...styles,
        clipPath: '${clipPath}',
        color: \`hsl(var(--\${color}-foreground))\`
      }}
      {...props}
    >
      {/* Selection Indicator */}
      {active && <div className="absolute left-0 top-0 bottom-0 w-1 bg-[hsl(var(--\${color}-base))]" />}
      
      {children || (
        <>
          <div className="flex-1 flex flex-col">
             <span className="font-medium text-sm">Item Component</span>
             <span className="text-xs opacity-70 font-mono">{version}</span>
          </div>
          <ChevronRight className="h-4 w-4 opacity-50 group-hover:translate-x-1 transition-transform" />
        </>
      )}
    </div>
  )
})

Component.displayName = "Item-${version}"

export default Component
`;
};

// Generate each version
VERSIONS.forEach(version => {
  const content = TEMPLATE(version);
  const filePath = path.join(TARGET_DIR, `${COMPONENT_NAME}-${version}.tsx`);
  fs.writeFileSync(filePath, content);
  console.log(`Generated ${COMPONENT_NAME}-${version}.tsx`);
});

// Generate index.tsx
const indexContent = `/**
 * Item Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';

// Fallback types if file doesn't exist
type ItemVersion = string;
interface ItemProps extends React.HTMLAttributes<HTMLDivElement> {
  version?: ItemVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  children?: React.ReactNode;
  active?: boolean;
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/${COMPONENT_NAME}.json');
} catch (e) {
  // console.warn('Config not found for ${COMPONENT_NAME}');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
${VERSIONS.map(v => `  '${v}': lazy(() => import('./${COMPONENT_NAME}-${v}')),`).join('\n')}
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-12 rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, ItemProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={\`p-4 border border-dashed border-red-500/50 bg-red-500/10 \${className}\`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackItem';

// Main Component
const ItemBase = React.forwardRef<HTMLElement, ItemProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
ItemBase.displayName = 'Item';

export const Item = ItemBase;

export default Item;
`;

fs.writeFileSync(path.join(TARGET_DIR, 'index.tsx'), indexContent);
console.log('Generated index.tsx');

// Update main index.ts export
const mainIndexInitPath = path.join(__dirname, '../src/ui/index.ts');
let mainIndexContent = fs.readFileSync(mainIndexInitPath, 'utf8');

// Check if already exported
if (!mainIndexContent.includes("export * from './components/item'")) {
    // Add to components section
    const exportStatement = "export * from './components/item';";
    // Find a good place to insert (e.g. after input-otp)
    if (mainIndexContent.includes("export * from './components/input-otp';")) {
        mainIndexContent = mainIndexContent.replace(
            "export * from './components/input-otp';",
            "export * from './components/input-otp';\n" + exportStatement
        );
    } else {
        // Append to end if specific place not found
        mainIndexContent += `\n${exportStatement}`;
    }
    fs.writeFileSync(mainIndexInitPath, mainIndexContent);
    console.log('Updated src/ui/index.ts with export');
}

console.log('Item regeneration complete.');
