/**
 * IconButton Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';
// import type { IconButtonProps, IconButtonVersion } from '../../types/components/icon-button.js';

// Fallback types if file doesn't exist
type IconButtonVersion = string;
interface IconButtonProps extends React.HTMLAttributes<HTMLElement> {
  version?: IconButtonVersion;
  variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info';
  type?: 'default' | 'outline' | 'solid' | 'ghost';
  [key: string]: any;
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/icon-button.json');
} catch (e) {
  // console.warn('Config not found for icon-button');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./icon-button-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./icon-button-holo-frame.tsx')),
  'data-panel': lazy(() => import('./icon-button-data-panel.tsx')),
  'circuit-board': lazy(() => import('./icon-button-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./icon-button-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./icon-button-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./icon-button-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./icon-button-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./icon-button-matrix-grid.tsx')),
  'neon': lazy(() => import('./icon-button-neon.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="animate-pulse bg-muted/20 w-full h-full min-h-[40px] rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, IconButtonProps>(({ 
  children, 
  className = '',
  version,
  ...props 
}, ref) => (
  <div ref={ref as any} className={`p-4 border border-dashed border-red-500/50 bg-red-500/10 ${className}`} {...props}>
    <span className="text-xs text-red-400 font-mono">Missing: {version}</span>
    {children}
  </div>
));
FallbackComponent.displayName = 'FallbackIconButton';

// Subcomponents

// Main Component
const IconButtonBase = React.forwardRef<HTMLElement, IconButtonProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
IconButtonBase.displayName = 'IconButton';

export const IconButton = IconButtonBase;

export default IconButton;

