/**
 * Sonner Component - Dynamic Renderer
 * Generated by script
 */

import React, { lazy, Suspense } from 'react';
import { Toaster as SonnerToaster } from "sonner"

// Fallback types if file doesn't exist
type SonnerVersion = string;
type ToasterProps = React.ComponentProps<typeof SonnerToaster> & {
    version?: SonnerVersion
    variant?: 'neutral' | 'primary' | 'success' | 'warning' | 'destructive' | 'info'
}

// Config import
let componentConfig: any = { versions: {} };
try {
  // @ts-ignore
  // componentConfig = require('../../config/components/sonner.json');
} catch (e) {
  // console.warn('Config not found for sonner');
}

// Dynamic imports for versions
const versionComponents: Record<string, any> = {
  'angular-corner': lazy(() => import('./sonner-angular-corner.tsx')),
  'holo-frame': lazy(() => import('./sonner-holo-frame.tsx')),
  'data-panel': lazy(() => import('./sonner-data-panel.tsx')),
  'circuit-board': lazy(() => import('./sonner-circuit-board.tsx')),
  'quantum-gate': lazy(() => import('./sonner-quantum-gate.tsx')),
  'tactical-hud': lazy(() => import('./sonner-tactical-hud.tsx')),
  'energy-shield': lazy(() => import('./sonner-energy-shield.tsx')),
  'terminal-window': lazy(() => import('./sonner-terminal-window.tsx')),
  'matrix-grid': lazy(() => import('./sonner-matrix-grid.tsx')),
  'neon-outline': lazy(() => import('./sonner-neon-outline.tsx')),
};

// Loading Skeleton
const LoadingSkeleton: React.FC = () => (
  <div className="fixed bottom-4 right-4 w-[356px] h-[60px] bg-muted/20 animate-pulse rounded" />
);

// Fallback Component
const FallbackComponent = React.forwardRef<HTMLElement, ToasterProps>(({ 
  version,
  ...props 
}, ref) => (
  <SonnerToaster {...props} />
));
FallbackComponent.displayName = 'FallbackSonner';

// Main Component
const SonnerBase = React.forwardRef<HTMLElement, ToasterProps>(({ 
  version = 'angular-corner',
  ...props 
}, ref) => {
  const VersionComponent = versionComponents[version];
  
  if (!VersionComponent) {
    return <FallbackComponent ref={ref} version={version} {...props} />;
  }

  return (
    <Suspense fallback={<LoadingSkeleton />}>
      <VersionComponent ref={ref} {...props} />
    </Suspense>
  );
});
SonnerBase.displayName = 'Sonner';

export const Sonner = SonnerBase;

export default Sonner;


